# Generated by Django 4.2.11 on 2024-04-08 00:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allowance_app',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('date', models.DateField(default=datetime.date.today)),
                ('allowance_no_debt', models.DecimalField(default=25,decimal_places=2, max_digits=10000)),
                ('allowance_debt', models.DecimalField(default=25,decimal_places=2, max_digits=10000)),

            ],
        ),
    ]
