# Generated by Django 4.2.11 on 2024-06-12 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allowance_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowance_app',
            name='allowance_debt',
            field=models.DecimalField(decimal_places=2, default=25, max_digits=10000),
        ),
        migrations.AddField(
            model_name='allowance_app',
            name='allowance_no_debt',
            field=models.DecimalField(decimal_places=2, default=25, max_digits=10000),
        ),
    ]
