# Generated by Django 4.2.11 on 2024-06-13 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allowance_app', '0002_allowance_app_allowance_debt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowance_app',
            name='unknown',
            field=models.TextField(blank=True, null=True),
        ),
    ]
