# Generated by Django 4.2.11 on 2024-06-23 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allowance_app', '0003_allowance_app_unknown'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allowance_input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowance_no_debt', models.DecimalField(decimal_places=2, default=25, max_digits=10000)),
                ('allowance_debt', models.DecimalField(decimal_places=2, default=25, max_digits=10000)),
            ],
        ),
        migrations.RemoveField(
            model_name='allowance_app',
            name='allowance_debt',
        ),
        migrations.RemoveField(
            model_name='allowance_app',
            name='allowance_no_debt',
        ),
        migrations.RemoveField(
            model_name='allowance_app',
            name='unknown',
        ),
    ]
