# Generated by Django 4.2.11 on 2024-06-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allowance_app', '0009_alter_allowance_input_allowance_debt_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Allowance_input',
        ),
        migrations.AddField(
            model_name='allowance_app',
            name='allowance_debt',
            field=models.IntegerField(blank=True, default=35, null=True),
        ),
        migrations.AddField(
            model_name='allowance_app',
            name='allowance_no_debt',
            field=models.IntegerField(blank=True, default=45, null=True),
        ),
    ]
