# Generated by Django 4.2.11 on 2024-06-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allowance_app', '0010_delete_allowance_input_allowance_app_allowance_debt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowance_app',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10000),
        ),
    ]
