# Generated by Django 4.2.11 on 2024-07-03 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allowance_app', '0012_alter_allowance_app_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allowance_input_app',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowance_no_debt', models.IntegerField(blank=True, default=45, null=True)),
                ('allowance_debt', models.IntegerField(blank=True, default=35, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='allowance_app',
            name='allowance_debt',
        ),
        migrations.RemoveField(
            model_name='allowance_app',
            name='allowance_no_debt',
        ),
    ]
