# Generated by Django 4.2.11 on 2024-07-06 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allowance_app', '0013_allowance_input_app_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowance_app',
            name='allowance_debt_spending',
            field=models.IntegerField(blank=True, default=35, null=True),
        ),
        migrations.AddField(
            model_name='allowance_app',
            name='allowance_no_debt_spending',
            field=models.IntegerField(blank=True, default=45, null=True),
        ),
    ]
