# Generated by Django 4.2.11 on 2024-07-08 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allowance_app', '0014_allowance_app_allowance_debt_spending_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowance_app',
            name='credit',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='allowance_app',
            name='debit',
            field=models.BooleanField(null=True),
        ),
    ]
