# Generated by Django 4.2.11 on 2024-07-08 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allowance_app', '0015_allowance_app_credit_allowance_app_debit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allowance_app',
            name='debit',
        ),
    ]
