# Generated by Django 4.2.11 on 2024-07-08 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allowance_app', '0016_remove_allowance_app_debit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowance_app',
            name='credit',
            field=models.BooleanField(blank=True),
        ),
    ]
