# Generated by Django 4.2.11 on 2024-07-09 01:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allowance_app', '0017_alter_allowance_app_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowance_input_app',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
