# Generated by Django 4.2.11 on 2024-07-09 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allowance_app', '0018_allowance_input_app_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allowance_app',
            name='allowance_debt_spending',
        ),
        migrations.RemoveField(
            model_name='allowance_input_app',
            name='allowance_debt',
        ),
    ]
