# Generated by Django 4.2.11 on 2024-07-09 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allowance_app', '0019_remove_allowance_app_allowance_debt_spending_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowance_app',
            name='allowance_debt_spending',
            field=models.IntegerField(blank=True, default=35, null=True),
        ),
        migrations.AddField(
            model_name='allowance_input_app',
            name='allowance_debt',
            field=models.IntegerField(blank=True, default=35, null=True),
        ),
    ]
