# Generated by Django 4.2.11 on 2024-07-10 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allowance_app', '0020_allowance_app_allowance_debt_spending_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allowance_app',
            name='allowance_debt_spending',
        ),
        migrations.RemoveField(
            model_name='allowance_input_app',
            name='allowance_debt',
        ),
        migrations.AlterField(
            model_name='allowance_app',
            name='allowance_no_debt_spending',
            field=models.IntegerField(blank=True, default=25, null=True),
        ),
    ]
